### ISSUE TITLE
No Image Published for Release 2.0.10?

### ISSUE THREAD

**Issue by jsmythsci** [tiredofit/docker-spamassassin#13]
I'm looking at [DockerHub tags](https://hub.docker.com/r/tiredofit/spamassassin/tags) and there does not seem to have been a published version of 2.0.10:

![image](https://github.com/tiredofit/docker-spamassassin/assets/45214333/c78ddaed-89aa-48ad-b4d6-68ecebeef14b)

Was this intentional?

I looked at [the commit history](https://github.com/tiredofit/docker-spamassassin/commits/main) and it looks like there has only been 1 change since the 2.0.10 build, but as a matter of principle we do not use `latest` in our build scripts.

I could pull the latest image by its hash, but I'm not sure how DockerHub handles untagged images, so this could be risky. Even if it is safe, it makes maintenance more difficult. Without a pinned tag, there will be no easy way to determine what changed between our current version and the new `latest` version.

Appreciate your work maintaining this repo and welcome any feedback you may have.

**Comment by tiredofit** [comment]
Github has struggled with some stability issues over the past year - just looking at the https://github.com/tiredofit/docker-spamassassin/actions shows that 2.0.10 failed to build.. It's too late to restart that job now, so I can push a 2.0.11 and see if that builds.

**Comment by tiredofit** [comment]
Looks like it worked.. Enjoy!

**Comment by jsmythsci** [comment]
Awesome!

Really appreciate the quick turnaround here.

Thank you.
