### ISSUE TITLE
Access Forbidden on startup of docker container

### ISSUE THREAD

**Issue by 7homasSutter** [tiredofit/docker-spamassassin#5]
I just tried to get the docker container running with docker-compose but I always get an access forbidden error. It seems that the container attempts to open the link `https://registry.selfdesign.org/v2/docker/spamassassin/manifests/latest` which needs authentication. Is there a way to configure the authentication for this link or is this a bug?

```
docker-compose up
[+] Running 0/1
 ⠿ spamassassin-app Error                                                                                                                         1.3s
Error response from daemon: Head "https://registry.selfdesign.org/v2/docker/spamassassin/manifests/latest": denied: access forbidden
```

**Comment by tiredofit** [comment]
Have a peek at the new example. You should pulll. `tiredofit/spamassassin` instead, sorry , that was an error of a private registry.
