### ISSUE TITLE
Docker image size doesn't match between latest and 2.0.9.

### ISSUE THREAD

**Issue by arkag** [tiredofit/docker-spamassassin#7]
Not sure if this is the best place to ask about this, but I was hoping to get some clarification here, as I'm confused why latest doesn't match 2.0.9 in terms of size for images.

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/6749810/220456414-b9f591ef-35f2-438a-8294-9fda3f370b7a.png">

**Comment by tiredofit** [comment]
`:latest` just means that there has been a new build without a specific tag or version associated with it. You can see the commits here: https://github.com/tiredofit/docker-spamassassin/commits/main to see what has changed in between versioned releases. `:latest` can get you into all sorts of problems if the image has broken during an auto build process and hasn't been thoroughly tested..

My guess is that the base image itself has new features that I use were included into this descendant image.

**Comment by arkag** [comment]
Ah, okay. Frequently with official images I see latest being used to reference the most recent stable release. If this isn't the case for your images I can pin versions in my docker-compose for this.

**Comment by tiredofit** [comment]
For the most part the tags should match the latest tag but in some cases as above where I was hacking away at the github build scripts they can break apart. I think FWIW you are still safe on this image with :latest.

**Comment by arkag** [comment]
I didn't expect it to be a major change, so it's good to have it confirmed.

I have one other question somewhat related to this. How are SpamAssassin versions managed here? With your ClamAV image there are enough releases in your GitHub to see the version get bumped manually, but I don't see this for SA.

**Comment by tiredofit** [comment]
I'm relying on the Alpine in-built packages on this one and usually only performing additions to the image when the Alpine version changes. I'm actually not really using this image anymore in production so its just sitting here and getting the "keep the lights on" treatment.

**Comment by arkag** [comment]
Okay, that's good to know as well. Thank you!
